$CPAN::Config = {
    'build_cache' => q[10],
    'build_dir' => q[/home/nwertzberger/.cpan/build],
    'cache_metadata' => q[1],
    'cpan_home' => q[/home/nwertzberger/.cpan],
    'dontload_hash' => {  },
    'ftp' => q[/usr/kerberos/bin/ftp],
    'ftp_proxy' => q[],
    'getcwd' => q[cwd],
    'gpg' => q[/usr/bin/gpg],
    'gzip' => q[/bin/gzip],
    'histfile' => q[/home/nwertzberger/.cpan/histfile],
    'histsize' => q[100],
    'http_proxy' => q[],
    'inactivity_timeout' => q[0],
    'index_expire' => q[1],
    'inhibit_startup_message' => q[0],
    'keep_source_where' => q[/home/nwertzberger/.cpan/sources],
    'links' => q[],
    'make' => q[/usr/bin/make],
    'make_arg' => q[-j3],
    'make_install_arg' => q[-j3],
    'makepl_arg' => q[PREFIX=~/perl],
    'ncftp' => q[],
    'ncftpget' => q[],
    'no_proxy' => q[],
    'pager' => q[/usr/bin/less],
    'prerequisites_policy' => q[follow],
    'scan_cache' => q[atstart],
    'shell' => q[/bin/bash],
    'tar' => q[/bin/tar],
    'term_is_latin' => q[1],
    'unzip' => q[/usr/bin/unzip],
    'urllist' => [q[ftp://cpan.cs.utah.edu/CPAN/], q[ftp://ftp.uwsg.iu.edu/pub/perl/CPAN/], q[ftp://ftp.ndlug.nd.edu/pub/perl/]],
    'wget' => q[/usr/bin/wget],
};
1;
__END__
